-- MySQL Script generated by MySQL Workbench
-- Tue Apr 28 15:52:14 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema quiz
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema quiz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quiz` DEFAULT CHARACTER SET utf8 ;
USE `quiz` ;

-- -----------------------------------------------------
-- Table `quiz`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nivel_acesso` INT NOT NULL DEFAULT 2 COMMENT '1 - bloqueado\n2 - usuario\n3 - adm',
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(80) NOT NULL COMMENT 'Será utilizado como login de acesso',
  `senha` VARCHAR(60) NOT NULL COMMENT 'Será criptografada',
  `nascimento` DATE NULL,
  `pontuacao` INT NULL DEFAULT 0,
  `ativo` TINYINT NULL DEFAULT 1 COMMENT ' 0 - inativo\n 1 - ativo',
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz`.`categorias` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz`.`perguntas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz`.`perguntas` (
  `id_pergunta` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_categoria` INT NOT NULL,
  `pergunta` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id_pergunta`),
  INDEX `fk_perguntas_usuarios_idx` (`id_usuario` ASC),
  INDEX `fk_perguntas_categorias_idx` (`id_categoria` ASC),
  CONSTRAINT `fk_perguntas_usuarios`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `quiz`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_perguntas_categorias`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `quiz`.`categorias` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz`.`alternativas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz`.`alternativas` (
  `id_alternativa` INT NOT NULL AUTO_INCREMENT,
  `id_pergunta` INT NOT NULL,
  `resposta` VARCHAR(255) NOT NULL,
  `correta` TINYINT NOT NULL DEFAULT 0 COMMENT '0 - errada ou incorreta\n1 - certa ou correta',
  PRIMARY KEY (`id_alternativa`),
  INDEX `fk_respostas_perguntas_idx` (`id_pergunta` ASC),
  CONSTRAINT `fk_respostas_perguntas`
    FOREIGN KEY (`id_pergunta`)
    REFERENCES `quiz`.`perguntas` (`id_pergunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
