<?php
require_once('class/Constantes.php');
require_once('class/Helper.php');
require_once('class/Conexao.php');
require_once('class/Categoria.php');
require_once('class/Usuario.php');
require_once('class/Pergunta.php');
require_once('class/phpmailer/Email.php');
require_once('class/Banner.php');
?>